CXX = g++
CXXFLAGS = -O2 -std=c++17 -Wall -Wextra -pthread
TARGET = array-summary
SRC = array-summary.cpp


.PHONY: all clean


all: $(TARGET)


$(TARGET): $(SRC)
$(CXX) $(CXXFLAGS) -o $(TARGET) $(SRC)


clean:
rm -f $(TARGET)
